name: Test GCD Script
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
      - name: テストスクリプトの実行
        run: |
          chomd +x gcd.sh
          chomd +x test.sh
          ./test.sh
